### ISSUE TITLE
Discussion: Cover image/s

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#201]
We need cover image/s! (Preferably images/photos that we've created/taken.)

Please add ideas below.

**Comment by gvwilson** [comment]
Boats

![226377029](https://user-images.githubusercontent.com/911566/67619802-18a06800-f7ce-11e9-8fc7-8ccfe39d417b.jpg)
![4006714214](https://user-images.githubusercontent.com/911566/67619803-18a06800-f7ce-11e9-9b8b-16aa1c6975f7.jpg)
![5573980030](https://user-images.githubusercontent.com/911566/67619804-18a06800-f7ce-11e9-8bcf-157d72c58d9f.jpg)
![23283063256](https://user-images.githubusercontent.com/911566/67619805-18a06800-f7ce-11e9-9aad-499a3d456160.jpg)

**Comment by k8hertweck** [comment]
Thumbs up here for tugboats! (last pic in the series above)

I think it makes sense because they are utilitarian, and we're talking about making python packages.

**Comment by k8hertweck** [comment]
I also think the speedboat (second pic) should be for rse-R, and the other two for intro books.

BOAT BOOKS FTW

**Comment by cwickham** [comment]
Another vote for the tugboats.

For rse-R, I'm wondering if we can find something that also indicates working as a team, maybe something like people working a sailboat? (This was the closest I could find https://unsplash.com/photos/gKkQj-Y-XD0)

**Comment by lwjohnst86** [comment]
Love the tugboats too! And sailboat for R :grin:

**Comment by joelostblom** [comment]
I like the tugboats and rowboats pictures!
