### ISSUE TITLE
Figure out how to display PNG/JPG screenshots without rescaling

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/py-rse#255]
Screenshots have to be displayed 1:1 or they will look blurry when printed. LaTeX doesn't make this easy, and putting Bookdown on top of it doesn't make it any easier.

**Comment by lwjohnst86** [comment]
Could you expand on this? I'm not 100% certain I understand.

**Comment by gvwilson** [comment]
Screenshots are 70 dpi by default on Mac, but that looks grainy when printed at 300 dpi (typical pro-quality publishing). We can leave this 'til the very end - no matter what we do, the production team will ask for some changes.
