### ISSUE TITLE
Discussion: Teach `.format()` or f-strings (f')

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/py-rse#342]
We currently use `'String with {var}'.format(var)` everywhere we need to format strings with variables. f-strings (`f'String with {var}'`) are arguably easier on the eyes and a bit more intuitive to learn. They have been supported since 3.6, which seems like a pretty safe distance to not worry too much about learners running too old versions of Python. Thoughts?

<details>
<summary>Current occurrences of format</summary>
<pre>
bin/nbspref.py:                    print('{}: {}'.format(f, m))
bin/crossrefs.py:    figures = set(['fig:{}'.format(x) for sublist in text for x in FIGURE.findall(sublist)])
bin/crossrefs.py:    report('{}: used but not defined'.format(title), refs - (headings | figures))
bin/chapters.py:        check('config and {}'.format(filename), config, values)
bin/chapters.py:    assert len(lines) == 1, 'No match for {}'.format(makefile_key)
bin/chapters.py:        assert CONFIG_KEY in config, '{} not found in {}'.format(CONFIG_KEY, config_file)
bin/chapters.py:        assert len(set([x[0] for x in raw])) == 1, 'Inconsistent directory names in {}'.format(filename)
bin/chapters.py:            print('{}: {}'.format(title, subtitle))
bin/chapters.py:                print('  {}'.format(i))
r-rse/correct.Rmd:    print('{:2d} {:22.21f} {:22.21f}'.format(i, total, total-expected))
r-rse/correct.Rmd:            print('{:22.21f} {:2d} {:22.21f} {:22.21f}'.format(bound, i, total, expected))
r-rse/correct.Rmd:    logger.write('text_to_words.py,num_lines,{}\n'.format(num_lines))
r-rse/correct.Rmd:    logger.write('text_to_words.py,num_words,{}\n'.format(num_words))
r-rse/correct.Rmd:    logger.write('word_count.py,num_words,{}\n'.format(num_words))
r-rse/correct.Rmd:    logger.write('word_count.py,num_distinct,{}\n'.format(len(count)))
r-rse/style.Rmd:    result = '<{}'.format(tag)
r-rse/style.Rmd:        result += ' {}="{}"'.format(key, kwargs[key])
r-rse/style.Rmd:    print('{} {} <{}>'.format(first, last, email))
py-rse/errors.Rmd:        print('1/{} == {}'.format(denom, result))
py-rse/errors.Rmd:        print('{} has no reciprocal'.format(denom))
py-rse/errors.Rmd:        print('1/{} == {}'.format(denom, result))
py-rse/errors.Rmd:        print('{} has no reciprocal: {}'.format(denom, error))
py-rse/errors.Rmd:        print('1/{} == {}'.format(denom, result))
py-rse/errors.Rmd:        print('index {} out of range'.format(i))
py-rse/errors.Rmd:        print('{} has no reciprocal: {}'.format(denom, error))
py-rse/errors.Rmd:            raise ValueError('negative values not supported: {}'.format(number))
py-rse/errors.Rmd:        print('exception: {}'.format(error))
py-rse/errors.Rmd:    print('Error trying to sum reciprocals: {}'.format(error))
py-rse/errors.Rmd:        print('No log directory {}'.format(LOG_DIR), file=sys.stderr)
py-rse/errors.Rmd:        print('Unable to write log message to {}: {}'.format(path, error))
py-rse/errors.Rmd:    raise ValueError('Bad value: {}'.format(val))
py-rse/errors.Rmd:    raise ValueError('Value {} is None'.format(val))
py-rse/errors.Rmd:    raise ValueError('Value {} is out of range ({}, {})'.format(val, min_val, max_val))
py-rse/errors.Rmd:    raise ValueError('Value {} is odd'.format(val))
py-rse/errors.Rmd:    raise ValueError('Value {} is not less than previous value {}'.format(val, prev_val))
py-rse/errors.Rmd:    print('Unable to find or read file {}'.format(filename))
py-rse/errors.Rmd:    print(ERROR_MESSAGES['cannot_read_file'].format(filename))
py-rse/errors.Rmd:        print('Current alpha value {}'.format(alpha))
py-rse/package-py.Rmd:print('generated distribution: {}'.format(generated))
py-rse/package-py.Rmd:print('passes test with default tolerance: {}'.format(is_zipf(generated)))
py-rse/package-py.Rmd:print('passes test with tolerance of 1.0: {}'.format(is_zipf(generated, rel=1.0)))
py-rse/package-py.Rmd:        print('{}: {}'.format(result, values))
py-rse/package-py.Rmd:        print('{}: {}'.format(result, values))
py-rse/package-py.Rmd:        print('{}: {}'.format(result, values))
py-rse/package-py.Rmd:        print('{}: {}'.format(result, values))
py-rse/correct.Rmd:    print('{:2d} {:22.21f} {:22.21f}'.format(i, total, total-expected))
py-rse/correct.Rmd:            print('{:22.21f} {:2d} {:22.21f} {:22.21f}'.format(bound, i, total, expected))
py-rse/correct.Rmd:    logger.write('text_to_words.py,num_lines,{}\n'.format(num_lines))
py-rse/correct.Rmd:    logger.write('text_to_words.py,num_words,{}\n'.format(num_words))
py-rse/correct.Rmd:    logger.write('word_count.py,num_words,{}\n'.format(num_words))
py-rse/correct.Rmd:    logger.write('word_count.py,num_distinct,{}\n'.format(len(count)))
py-rse/style.Rmd:    result = '<{}'.format(tag)
py-rse/style.Rmd:        result += ' {}="{}"'.format(key, kwargs[key])
py-rse/style.Rmd:    print('{} {} <{}>'.format(first, last, email))
src/package-py/03a/zipf.py:        print('{}: {}'.format(result, values))
src/package-py/02/zipf.py:        print('{}: {}'.format(result, values))
src/package-py/02/use.py:print('generated distribution: {}'.format(generated))
src/package-py/02/use.py:print('passes test with default tolerance: {}'.format(is_zipf(generated)))
src/package-py/02/use.py:print('passes test with tolerance of 1.0: {}'.format(is_zipf(generated, rel=1.0)))
src/package-py/01/use.py:print('generated distribution: {}'.format(generated))
src/package-py/01/use.py:print('passes test with default tolerance: {}'.format(is_zipf(generated)))
src/package-py/01/use.py:print('passes test with tolerance of 1.0: {}'.format(is_zipf(generated, rel=1.0)))
src/package-py/09/bin/check_zipf.py:        print('{}: {}'.format(result, values))
src/package-py/08/bin/check_zipf.py:        print('{}: {}'.format(result, values))
src/package-py/03b/zipfpy/zipf.py:        print('{}: {}'.format(result, values))
src/package-py/07/zipfpy/check.py:        print('{}: {}'.format(result, values))
src/package-py/06/zipfpy/check.py:        print('{}: {}'.format(result, values))
src/package-py/10/bin/check_zipf.py:        print('{}: {}'.format(result, values))
src/package-py/03c/zipfpy/check.py:        print('{}: {}'.format(result, values))
src/package-py/04/zipfpy/check.py:        print('{}: {}'.format(result, values))
</pre>
</details>

**Comment by DamienIrving** [comment]
I've seen/heard a number of people raving about f strings lately, so I'd be supportive of using them throughout. 

In the novice book I guess we could briefly mention the various different options for string formatting.

**Comment by gvwilson** [comment]
:+1: for f-strings - the `.format` stuff was mine, but it's old-fashioned now.

**Comment by joelostblom** [comment]
Good, I will PR when the current PRs have closed since there is a lot of new material under review currently

**Comment by k8hertweck** [comment]
We've decided on f-strings for the intermediate materials, although we'll need to update the novice materials to match.
