### ISSUE TITLE
GitHub for our characters (Amira and Sami) 

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#359]
(This issue was motivated by #349 relating to the Python RSE volume.)

Once the content of the git chapters is settled, we'll need to create a `zipf` git repo and go through each commit one-by-one as it's presented in the book so we can get a consistent commit history. We need that for generating the `git log` output (down to the precise SHA-1 hash identifier for each commit) and we'll also need it for GitHub screenshots. 

To help with the GitHub screen shots I've created GitHub accounts for Amira Khan (the main character in the Python RSE volume) and Sami Virtanen (because we need a second person in the git advanced chapter for teaching pull requests). Here are the accounts (I've got the login details if you need them):

https://github.com/amira-khan/zipf
https://github.com/sami-virtanen

**Comment by lwjohnst86** [comment]
Really really like this idea! And we could actually then use Git tags to mark the start (or end) of each chapter, as a reference and to pull the directory tree structure in from (related to #310).

**Comment by DamienIrving** [comment]
There might be tools out there for creating artificial git histories (e.g. with nicely spaces time stamps) - @gvwilson is going to investigate (see #364).

**Comment by k8hertweck** [comment]
We have a repo for Amira's zipf project, with complete version history: https://github.com/amira-khan/zipf

Most figures are updated to show the process of creating this repo (though #405 remains). 

I'd be happy to update the text output in the Git chapters (e.g., `git log`) to reflect the SHA identifiers if there aren't going to be subsequent changes to the repo. 

The repo only includes the code up through the end of the git chapters, though. Should I go through and add a commit for each of the subsequent chapters, so the final project is shown? We could still include tags to the commits representing the end of each chapter for convenience.

**Comment by DamienIrving** [comment]
Eventually I think we do need to go through and add every commit for the remainder of the chapters, because there are a few places where we will need to update the existing screen shots (which are taken from my personal github account) with screen shots taken from Amira's account:
- Figure 11.4: A screenshot from Travis CI linked to Amira's GitHub account
- Figure 12.1: A tagged release of Amira's GitHub account

However, I think we should wait until the very end of the publication/review process to do this. At the moment there are a bunch of exercises in the second half of the book that don't have solutions. Some of the solutions should/will be incorporated into the final `collate.py`, `countwords.py`, `plotcounts.py` and/or `utilities.py` scripts, so if we did all the commits now we might have to undo/re-do them later.
