### ISSUE TITLE
Add screenshot of simple bug report from teams.Rmd

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/py-rse#405]
@DamienIrving writes about `teams.Rmd`:

1.  Once we've created a zipf directory in Amira's repo, put the text from this bug report into an actual issue at that repo and screenshot it. https://github.com/amirakhan

2. Once we've created a bug report/issue in Amira's repo, screenshot the drop down labels menu to illustrate what we're talking about in this labels section.

**Comment by gvwilson** [comment]
Can someone with access to Amira's acc't please get a screenshot for this?

**Comment by k8hertweck** [comment]
Addressed in #560

**Comment by k8hertweck** [comment]
resolved by 2ea176b
