### ISSUE TITLE
Re-do home page

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/py-rse#438]
The "Merely Useful" GitHub page needs a makeover.

**Comment by lwjohnst86** [comment]
Should it link to all the other material or should we revise so it shows only the content of the py-rse?

**Comment by DamienIrving** [comment]
In the [meeting on 13 August](https://github.com/merely-useful/merely-useful.github.io/wiki/Meeting-agenda-2020-08-13) we tagged @lwjohnst86 to handle the home page.

**Comment by lwjohnst86** [comment]
Considering we've moved out all the other books into their own repos, what do you all think about either:

1. Keeping this repo name as is?
2. Renaming to `py-rse` and creating another repo with the current name and make a website linking to all the other books?

**Comment by cwickham** [comment]
I'd be in favor of 2.

**Comment by lwjohnst86** [comment]
Ok, renaming now! Fix your remotes everyone :grin:

**Comment by gvwilson** [comment]
What remote do we rename to what?

**Comment by lwjohnst86** [comment]
`git remote set-url origin git@github.com:merely-useful/py-rse.git`

or if you have this repo as upstream, replace with upstream

**Comment by lwjohnst86** [comment]
So just to clarify, now we'd like a home page for Merely Useful for the four books together? Like to show off and link all four books?

**Comment by DamienIrving** [comment]
@lwjohnst86 Yep, I think that's the idea - a homepage at https://merely-useful.github.io/. I think that page will need some kind of blurb discussing what stage of development each book is at (and how to get involved).

**Comment by lwjohnst86** [comment]
I've got something up! https://merely-useful.github.io/ I didn't add much text and descriptions to it, let me know ideas and things to add in the new repo https://github.com/merely-useful/merely-useful.github.io (note, I am no web designer, so very much open to ideas about appearance etc).
