### ISSUE TITLE
Examples of good code provenance

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#453]
We currently have an exercise in the Provenance chapter that reads as follows:

### Evaluate a project's code provenance {#provenance-ex-eval-code}

The GitHub repository https://github.com/borstlab/reversephi_paper/ provides the code and data for the paper @leonhardt2017.  Browse the repository and answer the following questions:

1. Where is the software environment described? What files would you need to recreate the software environment? 
2. Where are the data processing steps described? How could you re-create the results included in the manuscript?
3. How are the scripts and data archived?  I.e. Where can you download the version of the code and data as it was when the manuscript was published?

To get a feel for the different approaches to code provenance, repeat steps 1-3 for... [TODO: List a few more papers.] 

We need to complete the TODO with a few papers that preferably show a diverse range of approaches to documenting the software environment, notebooks/scripts and computational data processing steps associated with a given research paper. Please add suggested papers to this issue.

**Comment by DamienIrving** [comment]
I'm going to selfishly nominate [Irving et al (2019)](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2019GL082015), which has an associated [Figshare page](https://figshare.com/articles/Anthropogenic_aerosols_greenhouse_gases_and_the_uptake_and_storage_of_excess_heat_in_the_climate_system_supplementary_metadata/7575830/3) with all the associated code provenance stuff.

**Comment by k8hertweck** [comment]
[This paper](https://github.com/blab/h3n2-reassortment) by Trevor Bedford's lab is interesting because it uses previously published data and has a brief description of a pre-processing pipeline, thought the code provenance is largely the same as the original paper linked here.

**Comment by k8hertweck** [comment]
[This](https://datadryad.org/stash/dataset/doi:10.5061/dryad.1jwstqjrd) is another interesting example from DataDryad, which presents code/data as an R package downloadable from that link. I haven't inspected it closely, and it doesn't seem to have been published yet (FRESH DATA) but I imagine there are other examples in Dryad I can search for if this seems like a reasonable type of example.

**Comment by cwickham** [comment]
First example looks good.  If we think it's too similar to the current example, I'd be happy to swap it out...i.e. I'd rather point to efforts where we know the researchers, rather than random ones I found on the internet.

I like the second example @k8hertweck too, mostly because I would know what to do with this package (e.g. how to install it), but who knows what a Python user might make of it.  I.e. it's good to remember the people who want to replicate your work, may not work in the same language as you.

**Comment by gvwilson** [comment]
Can someone please add this in? @cwickham @k8hertweck would you like to take it on?

**Comment by cwickham** [comment]
I'll take this.
