### ISSUE TITLE
Potential reviewers

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#455]
We need to make a list of potential reviewers of the book. As well as suggested names, please include a brief overview of the person's background to assist those of us who aren't familiar with their work.

**Comment by DamienIrving** [comment]
The list we gave to Taylor and Francis earlier in the process included the following people:

**Lorena Barba** 
https://lorenabarba.com/
<labarba@email.gwu.edu>
Professor of mechanical and aerospace engineering at the George Washington University, leading a research group in computational fluid dynamics, computational physics and high-performance computing. Member of the Board of Directors for NumFOCUS. Associate Editor in Chief of the Journal of Open Source Software.

**James Hetherington**
https://www.turing.ac.uk/people/researchers/james-hetherington
<jhetherington@turing.ac.uk>
Director of e-Infrastructure at UK Research and Innovation. He was previously Director of Research Engineering at The Alan Turing Institute and prior to that Director of the Research Software Development Group at UCL.

**Christopher Holdgraf**
https://predictablynoisy.com/
<choldgraf@berkeley.edu>
Fellow at the Berkeley Institute for Data Science and a member of Project Jupyter as well as the Binder Project.

**Aleksandra Nenadic**
https://www.software.ac.uk/about/staff/person/aleksandra-nenadic
<a.nenadic@manchester.ac.uk>
Training Lead at the Software Sustainability Institute.

**Matt Turk** 
https://sites.google.com/site/matthewturk/
<matthewturk@gmail.com>
Assistant Professor at the School of Information Sciences at University of Illinois Urbana-Champaign and an Assistant Professor in the Astronomy department at UIUC. Numfocus, SciPy conference etc involvement.

**Jason Williams**
https://jasonjwilliamsny.github.io/profile/
<williams@cshl.edu>
Bioinformatics, Carpentries, etc.

**Comment by gvwilson** [comment]
**Christina Koch**
https://christinalk.github.io/
koch.christinal@gmail.com
HPC facilitator at the University of Wisconsin, very active in the Carpentries community for many years.

**Comment by gvwilson** [comment]
**Ahmadou Dicko**
https://www.ahmadoudicko.com/
dicko.ahmadou@gmail.com
Statistical consultant based in Senegal.

**Comment by gvwilson** [comment]
**Dhavide Aruliah**
https://dhavide.github.io/
dhavide@gmail.com
Head of training at Quansight.
