### ISSUE TITLE
"References" heading does not show up in PDF

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/py-rse#464]
1.  `make pdf`
2.  Look in the ToC: no heading "References".
3.  Look at the end of the book: the references are formatting as a continuation of the final appendix.

I tried removing the `if html_output` in `references.Rmd` - that made the heading appear in the PDF, but:

1.  It still doesn't appear in the ToC.
2. It disappears from the HTML version.

**Comment by lwjohnst86** [comment]
It now is there as Appendix N in the pdf and also is in the HTML version.
