### ISSUE TITLE
Chapter headings in HTML ToC for solutions are wrong

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/py-rse#474]
`make html` then view:

![Screen Shot 2020-09-09 at 11 37 57 AM](https://user-images.githubusercontent.com/911566/92620742-feaa2f80-f290-11ea-848e-29529a816047.png)

**Comment by lwjohnst86** [comment]
Weird... I'll figure it out Friday

**Comment by lwjohnst86** [comment]
Hm, I think this is an issue with the fact that `\@ref` includes a link to a section, which is exactly what the TOC does too. So the TOC can't have two href links in the same space. I'll look into other ways of getting the number displayed without including the href.
