### ISSUE TITLE
Layout issues with HTML title page

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/py-rse#486]
1.  We need to insert the dedication from `includes/before_body.tex` into the HTML version _without_ duplicating it in the PDF version.

2. The tugboat image on the first page of the HTML version seems awkwardly placed - can we instead emulate something like http://js4ds.org/ ?

![Screen Shot 2020-09-13 at 7 31 53 AM](https://user-images.githubusercontent.com/911566/93017009-834bc500-f593-11ea-998c-d6d7eeb312ee.png)

**Comment by lwjohnst86** [comment]
Yea, I was mimicking what books like https://r4ds.had.co.nz/. I could also make it like https://bookdown.org/yihui/bookdown/... I'll test out your suggestion, just not sure it will look good with the gitbook format.
