### ISSUE TITLE
bug in glossary reference translation

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/py-rse#490]
Spotted 17:00 Eastern on 2020-09-14 (look at bullet point 2). The `\gref{Git}{git}` isn't translating.
![Screen Shot 2020-09-14 at 5 02 42 PM](https://user-images.githubusercontent.com/911566/93137926-3b6c9100-f6ac-11ea-9534-3e725efe6b3e.png)

**Comment by lwjohnst86** [comment]
Ah, I fixed that bug in the Prerequisites https://merely-useful.github.io/py-rse/index.html#intro-personas didn't see there was a duplicate in Appendix E. Not sure why it happens, but when `\gref` is used alone on a line, it disappears. Simplest fix I did was do:

    - \gref{Git}{git} version control

**Comment by gvwilson** [comment]
Pandoc labels the parse node as a different type if it's all by itself vs. part of a sentence. Fixed the Lua to catch it.
