### ISSUE TITLE
Bug in filesystem figure

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#500]
In [`figures/bash-basics/sample-filesystem.png`](https://github.com/merely-useful/py-rse/blob/book/figures/bash-basics/sample-filesystem.png) there's a `/Users/tmp/` directory, but later on when the following command is run there's no `tmp` directory.

```
$ ls /Users
amira   jun     sami
```

**Comment by k8hertweck** [comment]
I have access to the original file; I’ll fix this too.
