### ISSUE TITLE
Create our own git commands figure

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#501]
[figures/git-cmdline/git-remote.png](https://github.com/merely-useful/py-rse/blob/book/figures/git-cmdline/git-remote.png) shows the common git commands (`add`, `commit`, `push`, etc) and how they relate to the current workspace, staging area, local git repo and the remote repo. I'm not sure where it came from and it contains some commands that we don't discuss in this book (e.g. `fetch`), so I think we need to make our own (slightly simpler) version.

**Comment by k8hertweck** [comment]
Oof, this has been on my to-do list. I got hung up on trying to get draw.io to play well. I’ll buckle down and make the revisions happen this weekend.

Related: are we still holding off on screenshots of the repo for later chapters? In other words, are we anticipating more changes to the code that will be necessary in Amira’s repo?

**Comment by DamienIrving** [comment]
Thanks, @k8hertweck. 

I think we should still hold off on screenshots for the later chapters. While the code is more or less settled now (I'm still working on some exercises that might make minor changes) if the reviewers come back with suggestions about how the code is written (e.g. we might have done something that isn't very pythonic) then things could change.

The order is probably something like:
1. Deal with reviewer comments
2. Read/review the book one last time ourselves
3. Settle 100% on all content (final version of code, exercises, narrative, etc)
4. Go through the entire book command by command, updating Amira's GitHub repo (and the associated screenshots and command line output blocks) as required
5. Tag a version 1.0 release in the repo

**Comment by k8hertweck** [comment]
Comments above from @DamienIrving on Amira's repo will be closed by #554

**Comment by k8hertweck** [comment]
Closing this since #359 covers this in more detail
