### ISSUE TITLE
Split the introduction chapter in two

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#506]
Most of the current introduction chapter is about course **details** (the big picture, license, audience, syllabus, acknowledgements, dedications). This content needs to be moved into a numberless prologue (perhaps called "Overview" or "Welcome"), along with a new "how to use this book" section (see below) and some text on how to contribute to the book.

Chapter 1 (which we might rename "Getting Started" or something) should then just contain the initial course **content**.
That includes the existing Project Structure content and possibly also the software installation and data download instructions currently in Appendix E and Section 1.2.1.

### How to use this book

Our suggestions on "how to use this book" could be as simple as -- "Work through each chapter, following along with the commands and changes described in the text. Try at least half of the exercises for each chapter" -- to something as complex as an appendix with suggestions for a suggested course plan, adapting these materials to a lecture, finding a mentor or someone to help you (if doing self-study), etc.

Other notes from the reviewer (@ChristinaLK) include:

- Emphasizing the presence of exercises and solutions, as well as recommendations for how to use them. I agree with the decision to include the exercises at the end of each chapter, but I think a note recommending that readers not wait until the end to check out some of the available exercises would be a good idea.

- Outlining the standard chapter format: introduction, content, exercises; identifying the callout box format as a mechanism to supplement the main flow of text.

### Cleaning up appendices

Once the new prologue is complete, we should be able to remove appendices A, B and C. See [this discussion](https://github.com/merely-useful/py-rse/pull/505/files#r518479206) for details.

**Comment by gvwilson** [comment]
@lwjohnst86 can you please do this one, since it involves figuring out how to unnumbered preface sections in Bookdown?

**Comment by lwjohnst86** [comment]
Sounds good.
