### ISSUE TITLE
A mental model for error handling

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#512]
Comment from the reviewer (@ChristinaLK):

"I had the most difficulty in following chapter 10 (Error Handling); it was the one chapter where I felt like I didn't have a sufficient mental model to understand the details of the chapter. I'm not sure whether the solution is for me to have a better understanding of Python or for the chapter to more explicitly generate a mental model for errors and exceptions."

@joelostblom has [offered](https://github.com/merely-useful/py-rse/pull/505/files#r520377282) to have a go at addressing this issue.

**Comment by joelostblom** [comment]
I will PR this tomorrow, sorry for the delay.

**Comment by ChristinaLK** [comment]
@joelostblom if you tag me when you submit the PR, I will make a best effort to review. :)

**Comment by gvwilson** [comment]
I believe #550 fixes this.
