### ISSUE TITLE
Proposal: change title

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/py-rse#529]
Following comments in #518, we have three proposals for a title:

1. *Research Software Engineering with Python* (current title)
2. *Research Software Engineering with Python: Building software that makes research possible* (same with subtitle)
3. *Writing Research Software with Python* (avoids the term "RSE")

Please vote for your favorite by adding a comment to this issue.

**Comment by lwjohnst86** [comment]
2 (though I'm also partial to 3 since I agree that "engineering" word could be a bit intimidating)

**Comment by cwickham** [comment]
2

**Comment by k8hertweck** [comment]
3

**Comment by joelostblom** [comment]
Slight preference for 2. But I don't really think I have enough expertise on book titles or RSE for my vote to count the same as others who do, so happy for it to be overridden with a good motivation for one of the other titles.

**Comment by gvwilson** [comment]
2
