### ISSUE TITLE
Check formatting of citations

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/py-rse#553]
Sometimes we use `@Nobl2009`, which produces `Noble (2009)`, but sometimes we use `[@Nobl2009]`, which produces `(Noble 2009)`. Is this deliberate, or should we do a pass to make them consistent?

**Comment by k8hertweck** [comment]
I suspect this isn't always deliberate, but that we can't assume consistency will solve it (some places may reference the author's name as a part of the narrative). This is normally the type of thing I'd love to do, but I won't be able to get to it till probably Sunday.

**Comment by DamienIrving** [comment]
This is deliberate. `@Nobl2009` is the equivalent of `\citet` (a textual citation) and `[@nobl2009]` is like `\citep` (a parenthetical citation).

**Comment by gvwilson** [comment]
Well, I'm glad I didn't "fix" it then :-)
