### ISSUE TITLE
Separate solutions files for each chapter

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#555]
`chapters/solutions.Rmd` is getting pretty large and unwieldy. 

We have dedicated `keypoints/` and `objectives/` directories with separate files for each chapter - we probably need to do the same thing for solutions.

**Comment by gvwilson** [comment]
:-1: `solutions.Rmd` is only slightly larger than `git-advanced.Rmd`, and since we're trying to wrap this, I think any surgery that doesn't materially affect the PDF is out of scope.

**Comment by lwjohnst86** [comment]
Yea, I agree with @gvwilson, I don't think its necessary at this point, even if its large.
