### ISSUE TITLE
EOF newline

### ISSUE THREAD

**Issue by k8hertweck** [merely-useful/py-rse#556]
Nothing in `bin/` in the Zipf's Law project directory currently includes a newline at the end of the file, though `requirements.txt` and files in `results/` do. Do we need to include a callout about this, especially since some text editors and git interfaces yell at users about it?

**Comment by k8hertweck** [comment]
[PEP8 standards](https://pep8.readthedocs.io/en/release-1.7.x/intro.html) include an expectation for an empty line: "W292 | no newline at end of file". Clearly this doesn't prevent the code from functioning as expected, though. I know our python code has been run through a linter; is there a reason why we haven't included empty lines?

I'm inclined to add a pop-out to the advanced shell chapter that suggests empty lines at the end of shell scripts, since using `cat` to print scripts without them makes them look crappy:

```bash
bash-3.2$ cat book_summary.sh 
# Get author information from a Project Gutenberg eBook.
# Usage: bash book_summary.sh /path/to/file.txt what_to_look_for
head -n 17 $1 | tail -n 8 | grep $2bash-3.2$ 
```

I'll need to know how to proceed before I continue developing Amira's repo.

**Comment by DamienIrving** [comment]
I think we should definitely include a newline at the end of all our bash scripts, python scripts and makefiles. For some reason `pycodestyle` didn't pick up that problem when I ran it on the python scripts in `zipf/bin`, but it should have.

A pop-out in the advanced shell chapter would work - for python scripts it might also be worth mentioning it in the "writing readable code" appendix.

**Comment by k8hertweck** [comment]
Great, I’ll include these items in #554 . Thanks for the confirmation!
