### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by k8hertweck** [merely-useful/py-rse#559]
Not sure how relevant these are right now, but keeping track as I proceed:

- `history` in [Chapter 3 key points](https://merely-useful.github.io/py-rse/bash-tools.html#bash-tools-keypoints) has an arrow in the middle
- [Fig 6.3](https://merely-useful.github.io/py-rse/git-cmdline.html#fig:git-cmdline-staging-area) has an icon that isn't appearing

**Comment by gvwilson** [comment]
I'll tackle these once @k8hertweck 's changes go in.

**Comment by gvwilson** [comment]
1. No arrow showing up in Chapter 3 key points in either PDF or HTML.
2. Fig 6.3 (The staging area in Git) looks good to me.
