### ISSUE TITLE
Should we publish our zipf package to PyPI and Read The Docs?

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#568]
In the packaging chapter we talk about uploading our `zipf` package to PyPI and documentation to Read The Docs, but we don't actually do it. I'm wondering if that's how we want to leave things, or if we do want to actually have it out there as a package (linked to Amira's GitHub account)?

One problem is that there's already a package called `zipf`, so we'd have to pick a different name like `zipfpy` or `pyzipf`.
https://pypi.org/project/zipf/
https://zipf.readthedocs.io

I guess the advantage of having our package out there is that if Amira doesn't publish it to PyPI and Read The Docs, someone reading our book will no doubt do it. In other words, even if we include call out boxes telling people following along that they shouldn't actually hit the red button and publish to PyPI and Read The Docs, someone will inevitably hit the red button.

What do people think? I hope I've raised this issue before @k8hertweck gets to the packaging chapter in #560...

**Comment by DamienIrving** [comment]
Putting our documentation up on Read The Docs will also force us to resolve #410

**Comment by DamienIrving** [comment]
@k8hertweck I you don't want to potentially mess up Amira's repo, I could update the relevant text/narrative in the packaging chapter by testing everything on a new `pyzipf` package created from my GitHub account, then once I'm confident it all works I could delete it and you could re-create with Amira's account?

**Comment by gvwilson** [comment]
:+1: good catch

**Comment by k8hertweck** [comment]
@DamienIrving This works! I'm still trying to figure out whether I can manage tags for different places in the repo, and making sure code is consistent among narrative/solutions/etc. Thanks for continuing with the proofreading and I'll await the info about PyPI!
