### ISSUE TITLE
Website build pandoc error

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#570]
Looks like the book isn't rendering online because of an issue installing pandoc?
https://github.com/merely-useful/py-rse/runs/1520063664

**Comment by joelostblom** [comment]
It seems like [pandoc has moved away from using `pandoc-citeproc` as a separate package](https://github.com/jgm/pandoc-citeproc#pandoc-citeproc) and [instead relies on the new citeproc library](https://github.com/jgm/citeproc). I checked the old GH actions jobs and they all have a warning that pandoc-citeproc is deprecated in homebrew, in your latest job it was finally disabled in homebrew so not longer avaialble.

I removed pandoc citeproc from the GitHub action and [it seems to be buiding fine now ](https://github.com/merely-useful/py-rse/runs/1521539165). I spot checked a few references and they seem to look ok, reopen if I missed something.

closed in https://github.com/merely-useful/py-rse/commit/b8b45362898455251b1bf02184a3a95b5a4df78a
