### ISSUE TITLE
PDF call-out boxes don't show link URLs

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/py-rse#572]
In the PDF document, the URL for links in call-out boxes don't show up in the footnotes.

Here's a couple of examples...

<img width="408" alt="Screen Shot 2020-12-13 at 10 30 11 am" src="https://user-images.githubusercontent.com/2062210/101999147-488e3000-3d2e-11eb-8599-d261fd62ede7.png">
<img width="406" alt="Screen Shot 2020-12-13 at 10 30 24 am" src="https://user-images.githubusercontent.com/2062210/101999149-4d52e400-3d2e-11eb-947b-1a3639b03aa0.png">

**Comment by gvwilson** [comment]
@lwjohnst86 can you please contact Shashi Kumar about this one (or I can if you'd rather)? This is very deep in the guts of the LaTeX class file...

**Comment by lwjohnst86** [comment]
For sure! I'll do that tomorrow morning

**Comment by lwjohnst86** [comment]
Shashi responded with fixes to the tex file, but I've gotta figure a way to include the fixes into the pandoc template... so might take a bit for this. Working on it though.

**Comment by gvwilson** [comment]
@lwjohnst86 if you can forward what Shashi sent to me I'll take a look.
