### ISSUE TITLE
Proposal: ship it

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/py-rse#582]
## Proposal

Send PDF as of ~~77ff4d62~~ https://github.com/merely-useful/py-rse/commit/097b3d32bd5f459b22efb2fc8874f84620276470 to publisher.

## Background

<img width="1037" alt="Screen Shot 2020-12-20 at 8 47 53 am" src="https://user-images.githubusercontent.com/911566/102785823-92999600-436c-11eb-8c0d-bba31a77cff9.png">

## Pros and Cons

**Pro:** We'll have it in before the end of the year.

**Con:** We still need to resolve two small LaTeX issues (off-by-one chapter/section links and URLs from callout boxes not showing up as footnotes), but I don't think we should let those hold us up.

## Alternatives

Wait, which at this point probably means we won't get it in until the new year.

**Comment by lwjohnst86** [comment]
I think we should ship after merging #584, that would fix that footnote problem.

**Comment by lwjohnst86** [comment]
PDF and tex have been built and added to https://github.com/merely-useful/py-rse/commit/097b3d32bd5f459b22efb2fc8874f84620276470. Let's ship this one.

**Comment by lwjohnst86** [comment]
We had some issues building the book, but its a latex package dependency issue that we don't really have control of. But otherwise, this is the version we should ship.
