### ISSUE TITLE
Cover template? Which one?

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/py-rse#589]
Which one do you guys prefer? From https://www.routledge.com/go/cover_templates?PageSpeed=noscript

I like 14 or 16.

**Comment by DamienIrving** [comment]
I agree that 14 and 16 are probably the best options. I'll vote for 14.

**Comment by k8hertweck** [comment]
14 for me too!

**Comment by cwickham** [comment]
14 looks good to me.
