### ISSUE TITLE
Tiny Mistake:  Misspelling in "to" 

### ISSUE THREAD

**Issue by Zrealshadow** [merely-useful/py-rse#604]
In  `teams.rmd` file, line 516.
![image](https://user-images.githubusercontent.com/30857435/106861943-67db8500-6701-11eb-8078-2b569857b91b.png)
I think here should be "referred to"

By the way, it's an excellent book, thanks for your work.

**Comment by DamienIrving** [comment]
All fixed. Thanks, @Zrealshadow!

Glad to hear you enjoyed the book.
