### ISSUE TITLE
Formatting: wrong section numbers in running headings

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/py-rse#609]
This is clearly a problem with the LaTeX template; all page numbers taken from the PDF returned by T&F on 2021-03-04:

-   p11: editor wants "1.4 Summary" instead of "1.6 Summary" in the u-   p-   per left, i.e., the first new section number not the last. (I'll call this 'wrong section number' below.)
-   p25: wrong section number (wants 2.3).
-   p33: wrong section number (wants 2.9).
-   p55: wrong section number (wants 3.6).
-   p91: wrong section number (wants 5.4).
-   p97: wrong section number (wants 5.6).
-   p99: wrong section number (wants 5.7).
-   p137: wrong section number (wants 6.10).
-   p177: wrong section number (wants 7.11).
-   p219: wrong section number (wants 9.3).
-   p231: wrong section number (wants 9.10).
-   p243: wrong section number (wants 10.5).
-   p259: wrong section number (wants 11.3).
-   p283: wrong section number (wants 12.1).
-   p291: wrong section number (wants 12.5).
-   p397: wrong section number (wants C.5).
-   p399: wrong section number (wants C.9).
-   p405: wrong section number (wants "D" throughout with no section numbers).
-   p409: wrong section number (wants E.1).
-   p411: wrong section number (wants E.3).
-   p421: wrong section number (wants F.2).
-   p423: wrong section number (wants F.3).
-   p435: wrong section number (wants F.5).
-   p445: wrong section number (wants G.2).
-   p453: wrong section number (wants I.1).
-   p471: wrong section number (wants "K. References").

**Comment by lwjohnst86** [comment]
As you say, its probably a problem of the template or the version they were using. I'll check it out tomorrow.

**Comment by lwjohnst86** [comment]
I've looked through the `krantz.cls` template trying to debug and figure out the problem and I have concluded I have no idea what's going on it there. We'll have to send to our latex expert.

**Comment by gvwilson** [comment]
:+1: Will you mail Shashi or do you want me to do it?

**Comment by lwjohnst86** [comment]
Doing it now :)

**Comment by gvwilson** [comment]
Closed by 681db757
