### ISSUE TITLE
Discussion: Citation links to wrong website

### ISSUE THREAD

**Issue by cheriimoya** [merely-useful/py-rse#644]
https://merely-useful.tech/ looks like it has been bought by some online casino thingy

![image](https://github.com/user-attachments/assets/8ea36638-fcd1-4bb8-8c3c-5661eb52df87)

**Comment by joelostblom** [comment]
Thanks for the heads up, I updated the citation link in https://github.com/merely-useful/py-rse/commit/62217e6606842ab9752fcf8e73954d1eb4a3cf07
